{% set version = "2.2.0" %}

package:
  name: triqs_dft_tools
  version: {{ version }}

source:
  url: https://github.com/TRIQS/dft_tools/releases/download/{{ version }}/dft_tools-{{ version }}.tar.gz
  sha256: 9836b2e4ef1ba6fef2d9276e0a43cf13a68b1626f0e4fae312fba5f7c888a49a

build:
  number: 0
  skip: True  # [win or py>30]

requirements:
  build:
    - cmake
    - make
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - triqs {{ '.'.join(version.split('.')[:2]) }}
  run:
    - {{ pin_compatible("triqs", max_pin="x.x") }}

test:
  imports:
    - triqs_dft_tools

about:
  home: https://triqs.github.io/dft_tools
  license: GPLv3
  license_family: GPL
  license_file: LICENSE.txt
  summary: 'Toolbox for ab initio calculations of correlated materials'

extra:
  recipe-maintainers:
    - wentzell
    - pgunn
